version: '2'
services:
  app:
    image: pajak/training
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-postgresql:5432/training # first oder of importance
    ports:
      - "80:80"
  app-postgresql:
    extends:
      file: postgresql.yml
      service: app-postgresql

