CREATE TABLE laporan
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    jumlah bigint NOT NULL,
    revision integer,
    wajib_pajak_perorangan_id bigint NOT NULL,
    CONSTRAINT laporan_pkey PRIMARY KEY (id),
    CONSTRAINT fkxnmbdvaaop2moyr7b9rwsgdq FOREIGN KEY (wajib_pajak_perorangan_id)
    REFERENCES public.wajib_pajak_perorangan (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
)