CREATE TABLE wajib_pajak_perorangan
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ktp character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT wajib_pajak_perorangan_pkey PRIMARY KEY (id),
    CONSTRAINT uk_k6awmltxwm0g3nt1a7d5xcfna UNIQUE (ktp)
    )