CREATE TABLE address
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    post_code integer NOT NULL,
    rt integer,
    rw integer,
    street_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    CONSTRAINT address_pkey PRIMARY KEY (id),
    CONSTRAINT fk8ncy9c0i8s8k1mtlbfappngb5 FOREIGN KEY (user_id)
    REFERENCES public.training_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    )